---
# main.yml | SNMP configuration

- name: SNMP | Installed
  apt: name={{ item }} state=present
  with_items: 
    - snmpd 
    - lm-sensors 
    - xinetd
    - libwww-perl
  notify:
    - restart snmpd

- name: SNMP | Instal optional packages
  apt: name={{ item }} state=present
  with_items: 
    - snmp-mibs-downloader
  failed_when: false

- name: SNMP | Check if UFW installed
  command: dpkg-query -s ufw
  register: ufw_check
  failed_when: ufw_check.rc > 1
  changed_when: false

- name: SNMP | Add Agent Port Exception to Firewall
  ufw: rule=allow proto=tcp direction=in to_port=36602
  when: ufw_check.rc == 0

- name: SNMP | Configure Observium Agent Directories
  file:
    name: /usr/lib/observium_agent
    state: directory
    recurse: true

- name: SNMP | Add Agent Scripts
  copy:
    src: files/agents/
    dest: /usr/lib/observium_agent/local

- name: SNMP | Fix Agent Permissions
  file:
    path: /usr/lib/observium_agent/local
    state: directory
    recurse: yes
    mode: 0755
    owner: root
    group: root

- name: SNMP | Add Xinetd Script
  template:
    src: templates/observium_agent_xinetd.j2
    dest: /etc/xinetd.d/observium_agent_xinetd
    owner: root
    group: root
  notify:
    - restart xinetd

- name: SNMP | Add Observium Agent Scripts
  copy: 
    src: files/{{ item }}
    dest: /usr/bin/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items:
    - observium_agent
    - distro

- name: SNMP | Configure Defaults
  template: src=templates/snmpd-default.j2 dest=/etc/default/snmpd force=yes backup=yes
  notify:
    - restart snmpd

- name: SNMP | Configure
  template: src=templates/snmpd.j2 dest=/etc/snmp/snmpd.conf force=yes backup=yes
  notify:
    - restart snmpd

- name: Started
  service:
    name: snmpd 
    state: started
